### ISSUE TITLE
Wrong dependency on phpunit-mock-objects

### ISSUE THREAD

**Issue by tehplague** [Codeception/Stub#1]
Please bump the version constraint for `phpunit/phpunit-mock-objects` to `^5.0` instead of `5.0`. Currently the installation of `codeception/stub` forces PHPUnit to downgrade from 6.5.5 to 6.5.1 because this package limits the version of `phpunit/phpunit-mock-object` to `5.0.0` (since `phpunit/phpunit-mock-objects: "^2.3|^3.0|^4.0|5.0"` is equal to `5.0.0` regarding 5.x versions).

As newer PHPUnit releases depend on at least version 5.0.5 your configuration is incompatible to them.

**Comment by DavertMik** [comment]
Thanks! Fixed in 1.0.1
