### ISSUE TITLE
Way to test method call with params

### ISSUE THREAD

**Issue by antonmarin** [Codeception/Stub#32]
#### What are you trying to achieve?

Trying to test if method called with my params using Stub utility.

``` php
$db = Stub::make(
            Connection::className(), 
            [
                'quoteColumnName' => Stub::exactly(2, function($params){
                    return $params[0];
                }),
            ],
            $this
        );
```
#### What do you get instead?

No way or documentation to do it

> Provide console output if related. Use `-vvv` mode for more details.

``` bash
# paste output here
```

> Provide test source code if related

``` php
// paste test
```
### Details
- Codeception version: 
- PHP Version:
- Operating System:
- Installation type: Phar || Composer
- List of installed packages (`composer show`)
- Suite configuration:

``` yml
# paste suite config here
```

**Comment by Kolyunya** [comment]
@antonmarin I was able to implement this using the following technique:

```php
Stub::exactly(2, function ($params) use (Tester $I) {
    $I->assertEquals($expected, $params);
    return $params[0];
});
```
