### ISSUE TITLE
Reversed MockObject_Generator condition BC break

### ISSUE THREAD

**Issue by dereuromark** [Codeception/Stub#5]
https://github.com/Codeception/Stub/pull/4 has introduced a sudden BC break and all our tests to now fail hard.

> Cannot declare class PHPUnit\Framework\MockObject\Generator, because the name is already in use     

The `!class_exists('PHPUnit\Framework\MockObject\Generator')` must be kept to avoid redeclare of such a shim method! Especially in a patch release.
We are now forced to lock down to 1.0.2 everywhere, as do all others most likely.

**Comment by Naktibalda** [comment]
What version of PhpUnit have you got installed?

**Comment by dereuromark** [comment]
Codeception PHP Testing Framework v2.3.9
Powered by PHPUnit 6.5.8 by Sebastian Bergmann and contributors.

**Comment by Naktibalda** [comment]
Thanks,

I reverted this change and released a new version.

**Comment by dereuromark** [comment]
Thank you for the quick revert/fix!

**Comment by Naktibalda** [comment]
@dereuromark Is there a particular reason why you are still using Codeception 2.3 ?

The root cause of your issue was that Codeception 2.3 creates the same aliases as Codeception/Stub in its [shim.php](https://github.com/Codeception/Codeception/blob/2.3.9/shim.php#L101) file.

I am thinking about reintroducing my change and adding conflict to composer.json
```json
"conflicts": {
  "codeception/codeception": "<2.4.0"
}
```

Or I could bump a major version and update Codeception 2.4 to use Stub 2.0.

**Comment by dereuromark** [comment]
You introduced other small regressions with the already discussed shim changes a while back.
Thus, in order to continue working, we had to lock down the versions here.

**Comment by Naktibalda** [comment]
What regressions?
I don't see any issues reported by you.

Please raise an issue if something is preventing you from using Codeception 2.4

**Comment by dereuromark** [comment]
It has to do with all the aliases dropped - https://github.com/Codeception/Codeception/compare/2.3.9...2.4.0#diff-b38cfe53d6f105ad2685aa4bc6f020deL19
You can sure make a new major and constraint to it, this way it is a bit less error prone and less unexpected to break. Pulling a patch shouldnt kill the whole testing suite :)

**Comment by Naktibalda** [comment]
Ah, you relied on Codeception providing aliases for `PHPUnit_Framework_` classes.
It shouldn't be too hard to update your code to use namespaced `PHPUnit\` classes.
